# Assignment Day 8 : Hands On Data Science Project with Python: Data Cleaning

### Achmad Luckyta Fasyni

#### Instruksi 1 : Load data yang sudah disediakan (telco_customer_churn.csv) kedalam dataFrame

In [192]:
import pandas as pd

#load data yang mempunyai format csv
df = pd.read_csv('telco_customer_churn.csv', sep=',')

#menampilkan lima baris teratas dari dataset
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

#### Instruksi 2 : Tunjukkan tipe data untuk semua kolom yang ada!

In [193]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

#### Instruksi 3 : Ubah nama kolom!
* CustomerID menjadi CustID
* Semua Kolom menjadi lowercase (huruf kecil)

In [194]:
#mengubah nama customerID menjadi custID
df = df.rename(columns = {'customerID' : 'custID'})

# mengubah semua nama kolom menjadi huruf kecil (lower case) 
df.columns = df.columns.str.lower()

df.head()

,custid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

#### Instruksi 4 : Hilangkan kata (automatic) dari value kolom PaymentMethod,
pastikan juga tidak ada spasi yang tersisa di awal/akhir! (hint: gunakan string functions)

In [195]:
#mengecek value dari kolom PaymentMethod yang memiliki "(automatic)"
df['paymentmethod'].value_counts()

Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: paymentmethod, dtype: int64

In [197]:
#Menghilangkan (automatic) dari value
df['paymentmethod'] = df['paymentmethod'].str.replace(' \(automatic\)', '')

#Menghilangkan spasi yang ada di awal dan di akhir value
df['paymentmethod'] = df['paymentmethod'].str.strip()

df.head()

,custid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer,42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Data Preprocessing

#### Instruksi 5 : One-hot encoding untuk kolom phoneservice dengan prefix â€˜serviceâ€™

In [198]:
#membuat one hot encoding dengan prefix 'service'
df = pd.get_dummies(df, columns=['phoneservice'], prefix='service')
df.head()

,custid,gender,seniorcitizen,partner,dependents,tenure,multiplelines,internetservice,onlinesecurity,onlinebackup,...,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,service_No,service_Yes
0,7590-VHVEG,Female,0,Yes,No,1,No phone service,DSL,No,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0
1,5575-GNVDE,Male,0,No,No,34,No,DSL,Yes,No,...,No,No,One year,No,Mailed check,56.95,1889.5,No,0,1
2,3668-QPYBK,Male,0,No,No,2,No,DSL,Yes,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,1
3,7795-CFOCW,Male,0,No,No,45,No phone service,DSL,Yes,No,...,No,No,One year,No,Bank transfer,42.30,1840.75,No,1,0
4,9237-HQITU,Female,0,No,No,2,No,Fiber optic,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,1

#### Instruksi 6 : Normalization untuk kolom monthlycharges

In [199]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()

df['monthlycharges_normalized'] = min_max_scaler.fit_transform(df[['monthlycharges']])
df.head()

,custid,gender,seniorcitizen,partner,dependents,tenure,multiplelines,internetservice,onlinesecurity,onlinebackup,...,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,service_No,service_Yes,monthlycharges_normalized
0,7590-VHVEG,Female,0,Yes,No,1,No phone service,DSL,No,Yes,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0,0.115423
1,5575-GNVDE,Male,0,No,No,34,No,DSL,Yes,No,...,No,One year,No,Mailed check,56.95,1889.5,No,0,1,0.385075
2,3668-QPYBK,Male,0,No,No,2,No,DSL,Yes,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,1,0.354229
3,7795-CFOCW,Male,0,No,No,45,No phone service,DSL,Yes,No,...,No,One year,No,Bank transfer,42.30,1840.75,No,1,0,0.239303
4,9237-HQITU,Female,0,No,No,2,No,Fiber optic,No,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,1,0.521891

In [206]:
#mengecek hasil normalisasi
df['monthlycharges_normalized'].describe()

count    7043.000000
mean        0.462803
std         0.299403
min         0.000000
25%         0.171642
50%         0.518408
75%         0.712438
max         1.000000
Name: monthlycharges_normalized, dtype: float64

range value dengan value min = 0 dan value max = 1 setelah dilakukan normalization

#### Instruksi 7 : Standardization untuk kolom totalcharges

In [200]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

#Tipe data totalcharges sebelumnya adalah object, maka kita harus mengubahnya menjadi numerik/float
#menghilangkan spasi yang mungkin ada di value
df['totalcharges'] = df['totalcharges'].str.replace(' ', '')
#mengubah tipe data ke numerik
df['totalcharges'] = pd.to_numeric(df['totalcharges'])
#menangani value NaN yang muncul. Jika ada NaN, maka akan diganti dengan mean dari totalcharges 
if df['totalcharges'].isnull().sum() != 0:
    df['totalcharges'] = df['totalcharges'].fillna(value=df['totalcharges'].mean())

#standardization process
df['totalcharges_standardized'] = std_scaler.fit_transform(df[['totalcharges']])
df.head()

,custid,gender,seniorcitizen,partner,dependents,tenure,multiplelines,internetservice,onlinesecurity,onlinebackup,...,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,service_No,service_Yes,monthlycharges_normalized,totalcharges_standardized
0,7590-VHVEG,Female,0,Yes,No,1,No phone service,DSL,No,Yes,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0,0.115423,-0.994971
1,5575-GNVDE,Male,0,No,No,34,No,DSL,Yes,No,...,One year,No,Mailed check,56.95,1889.50,No,0,1,0.385075,-0.173876
2,3668-QPYBK,Male,0,No,No,2,No,DSL,Yes,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,1,0.354229,-0.960399
3,7795-CFOCW,Male,0,No,No,45,No phone service,DSL,Yes,No,...,One year,No,Bank transfer,42.30,1840.75,No,1,0,0.239303,-0.195400
4,9237-HQITU,Female,0,No,No,2,No,Fiber optic,No,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,1,0.521891,-0.941193

In [204]:
#mengecek hasil standardization
df['totalcharges_standardized'].describe()

count    7.043000e+03
mean     7.358400e-17
std      1.000071e+00
min     -9.998503e-01
25%     -8.305558e-01
50%     -3.897629e-01
75%      6.637555e-01
max      2.826469e+00
Name: totalcharges_standardized, dtype: float64

nilai mean sudah bernilai 0 dan standar deviasi sudah bernilai 1 setelah dilakukan standardization